.PHONY: build
build:
	build/build_workbench.sh

# faster build for debugging/development purposes
#   on pedro's laptop the difference is around 14s vs 1min20s
build_dev:
	DEBUG=1 build/build_workbench.sh

# force build of bullseye
build_bullseye:
	VERSION_CODENAME='bullseye' build/build_workbench.sh

# remove all files generated by build iso
build_clean:
	rm -rf build/wbiso/*

install_WB_dependencies:
	# Add bullseye backports to install lshw=02.19* utility
	echo "deb http://deb.debian.org/debian bullseye-backports main contrib" | sudo tee /etc/apt/sources.list.d/backports.list
	sudo apt update
	# Install WB debian requirements
	cat requirements.debian.txt | sudo xargs apt install -y
	# Install WB python requirements
	sudo pip3 install -r requirements.txt