#!/bin/sh
# Load the keyboard layout specified in the configuration file
# if the file is given as an argument,
# or interactively ask for one and load it.
# It must be run as root.

set -e

if [ "$1" ]; then
    KEYBOARD_LAYOUT=$(sed -rn 's/^\s*KEYBOARD_LAYOUT\s*=\s*([^\s]+)\s*/\1/p' "$1")
fi

# To ease listing.
cd /usr/share/X11/xkb/symbols

while ! test -f "$KEYBOARD_LAYOUT"; do
    echo "Available keyboard layouts (us=American, es=Spanish, fr=French, de=German...):"
    echo
    find . -maxdepth 1 -type f | sed 's#./##' | xargs ls
    echo
    read -p "Please enter one of the keyboard layouts from above: " KEYBOARD_LAYOUT
done

# However loading files in there fails, and to avoid loading random files with
# a name starting with the same letters as a layout file, we just use an empty
# directory.
cd $(mktemp -d)
loadkeys "$KEYBOARD_LAYOUT"
cd - > /dev/null
rmdir $OLDPWD
