#!/usr/bin/python

# -*- coding: utf-8 -*-
import re
import sys
import os.path

sys.path.insert(0, os.path.abspath(os.path.dirname(os.path.dirname(__file__)))) 

from erwb.donator import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
