#!/usr/bin/env bash

set -e
set -o pipefail

nfsserver=$(sed -rn 's/.*\bnfsroot=([^:]+):.*/\1/p' /proc/cmdline)
echo "Mounting remote data directory in $nfsserver..."
echo "This will only work if Workbench is connected to a Box"
if [ "$nfsserver" ]; then
    mkdir -p /media/workbench-data
    mount -t cifs -o guest,uid=root,forceuid,gid=root,forcegid "//$nfsserver/workbench-data" /media/workbench-data
fi
exit 0